apiVersion: batch/v1
kind: Job
metadata:
  name: test-telemetrygen-job
  namespace: default
spec:
  template:
    metadata:
      annotations:
        workload: job
      labels:
        app: test-telemetrygen
    spec:
      containers:
      - command:
        - /telemetrygen
        - metrics
        - --otlp-insecure
        - --otlp-endpoint=test-opentelemetry-collector:4317
        - --metrics=5
        - --rate=1
        - --otlp-attributes=service.name="test-job"
        - --otlp-attributes=k8s.container.name="telemetrygen"
        - --otlp-attributes=k8s.container.restart_count="0"
        image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
        imagePullPolicy: IfNotPresent
        name: telemetrygen
        resources: {}
        securityContext: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
