name: telemetrygen-e2e-tests

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
env:
  # Make sure to exit early if cache segment download times out after 2 minutes.
  # We limit cache download as a whole to 5 minutes.
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ~1.20.8
          cache: false
      - name: Cache Go
        id: go-cache
        timeout-minutes: 5
        uses: actions/cache@v3
        with:
          path: |
            ~/go/bin
            ~/go/pkg/mod
          key: go-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
      - name: Install dependencies
        if: steps.go-cache.outputs.cache-hit != 'true'
        run: make -j2 gomoddownload
      - name: Build Docker Image
        run: |
          make docker-telemetrygen
      - name: export image to tar
        run: |
          docker save telemetrygen:latest > /tmp/telemetrygen.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: telemetrygen
          path: /tmp/telemetrygen.tar
  kubernetes-test:
    env:
      KUBECONFIG: /tmp/kube-config-otelcol-e2e-testing
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ~1.20.8
          cache: false
      - name: Cache Go
        id: go-cache
        timeout-minutes: 5
        uses: actions/cache@v3
        with:
          path: |
            ~/go/bin
            ~/go/pkg/mod
          key: go-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }} 
      - name: Install dependencies
        if: steps.go-cache.outputs.cache-hit != 'true'
        run: make -j2 gomoddownload
      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: kind
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: telemetrygen
          path: /tmp
      - name: Load Docker image
        run: |
          docker load --input /tmp/telemetrygen.tar
      - name: Kind load image
        run: |
          kind load docker-image telemetrygen:latest --name kind
      - name: run telemetrygen e2e tests
        run: |
          cd cmd/telemetrygen
          go test -v --tags=e2e

